### ISSUE TITLE
Live channels

### ISSUE THREAD

**Issue by PIXELSTURM** [lprot/movian-plugin-twitch#11]
Hi!

I've the problem to watch live streams. Gives an error 400.

Greets.

**Comment by AitoZ** [comment]
@PIXELSTURM You should be more specific, @lprot most of the streams work. I've noticed the same error mentioned above **on every CS:GO stream**. I think it also would make sense to upgrade the Twitch API to **v5**, the API version (**v3**) used right now is going to end the third-party support at the **12/31/18** as you can see [here](https://dev.twitch.tv/docs/v5).

**Comment by ImmortalJ** [comment]
This seems to be related to the recent change with ads. Some categories are exempt from the new ads and they work fine in the plugin.

**Comment by csgabe** [comment]
I think I fixed it for now, see pull request. It seems it's still not fixed. I'll need to read the Twitch API.

**Comment by PIXELSTURM** [comment]
Cool! There's movement. Thanks!

Still getting error 400.
I think switching to the v5 api would be fix this. Hope you have to time for this.

Keep on rocking!

**Comment by csgabe** [comment]
Now it should be fixed.

**Comment by ImmortalJ** [comment]
Thanks gabe! That was driving me crazy trying to figure it out... can't believe it was something so silly ;)

**Comment by AitoZ** [comment]
Thanks @csgabe it seems to work again.
