### ISSUE TITLE
Change resolution from Options menu

### ISSUE THREAD

**Issue by ImmortalJ** [lprot/movian-plugin-twitch#3]
I've been trying to find a way to change the video resolution from the options bar in this plugin and having very little success. I figured out how to add the MultiOpt to the menu, but the settings only last until you leave the page. It's okay for me, but I was thinking it would nice if someone could figure out a way to make the changes sync up with the plugin settings. Here is my commit: https://github.com/ImmortalJ/movian-plugin-twitch/commit/087c79689450bf505b526f0c531427a7225223f5

I don't think it is worthy of being merged in its current state. Do you know if this is possible to do?

**Comment by lprot** [comment]
Can you please make a pull request? Don't fofget to bump ver in plugin.json

**Comment by ImmortalJ** [comment]
I can, but like I said, I don't think it's ready to be pushed into the live plugin. Do you still want me to?

**Comment by lprot** [comment]
It doesn't break functionality so why not?

**Comment by csgabe** [comment]
Tried to make a fix for this. I've added a new setting "override default video quality". Defaults to off.
 If it's off, the video quality set from settings gets used, else the one from the pages, pull request:https://github.com/lprot/movian-plugin-twitch/pull/6

**Comment by ImmortalJ** [comment]
That is exactly the kind of fix I was trying to figure out. Thanks so much!
